# Generated by Django 4.2.6 on 2023-10-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=63)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('serial', models.CharField(default=0, max_length=50)),
                ('date1', models.DateField()),
                ('date2', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('wydano', 'Wydano'), ('w realizacji', 'W realizacji'), ('do wydania', 'Do wydania'), ('rezygnacja z naprawy', 'rezygnacja z naprawy'), ('utylizacja', 'Utylizacja')], max_length=64, null=True)),
                ('todo', models.CharField(max_length=255)),
                ('uwagi', models.CharField(blank=True, max_length=255, null=True)),
                ('naprawa', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klient', to='espresso.client')),
            ],
        ),
    ]
