# Generated by Django 4.2.6 on 2023-10-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espresso', '0003_client_uwagi'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('przyjeto', 'Przyjęto'), ('w realizacji', 'W realizacji'), ('wydano', 'Wydano'), ('do wydania', 'Do wydania'), ('rezygnacja z naprawy', 'Rezygnacja z naprawy'), ('utylizacja', 'Utylizacja')], max_length=64, null=True),
        ),
    ]
