# Generated by Django 4.2.6 on 2023-10-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espresso', '0004_client_is_processed_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=65),
        ),
    ]
